---
- name: Pacman Update
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install Bash
  pacman:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: set-ntp
  command: /usr/bin/timedatectl set-ntp on

- name: install packages
  pacman:
    name: "{{ packages }}"
    state: present
  tags:
    - packages

- name: create user group
  group:
    name: "{{ user.group }}"
    gid: "{{ user.gid }}"
    state: present

- name: create user
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    uid: "{{ user.uid }}"

- name: create user socket dir
  file:
    path: /run/user/{{ user.uid }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700

